import { Pet, Category } from './types';

export const CATEGORIES: Category[] = [
  { id: 'dogs', name: '小狗', icon: 'pets' },
  { id: 'cats', name: '小猫', icon: 'cruelty_free' },
];

export const PETS: Pet[] = [
  {
    id: 'mochi',
    name: '麻薯',
    breed: '金毛寻回犬',
    age: '2',
    ageUnit: '岁',
    gender: 'Male',
    distance: '2.5公里',
    image: 'https://images.unsplash.com/photo-1633722715463-d30f4f325e24?q=80&w=1000&auto=format&fit=crop',
    price: '$120',
    location: '加州圣莫尼卡',
    weight: '12公斤',
    description: '麻薯是个开心果，喜欢在沙滩上散步和玩捡球游戏。他对小孩子特别温柔，是我们收容所的宠儿。他已经训练好定点排泄，并懂得“坐下”和“待着”等基本指令。麻薯正在寻找一个永远的家，那里有无数的肚皮按摩和拥抱等着他。',
    shelterName: '快乐爪爪救助中心',
    shelterDistance: '2.5 英里外',
    shelterLogo: 'https://cdn-icons-png.flaticon.com/512/3047/3047928.png',
    tags: ['已打疫苗', '亲人', '对小孩友好'],
    category: 'dogs'
  },
  {
    id: 'charlie',
    name: '查理',
    breed: '金毛寻回犬',
    age: '2',
    ageUnit: '个月',
    gender: 'Male',
    distance: '1.2公里',
    image: 'https://images.unsplash.com/photo-1601979031925-424e53b6caaa?q=80&w=600&auto=format&fit=crop',
    price: '$200',
    location: '上海市徐汇区',
    weight: '3公斤',
    description: '查理是一只非常活泼的小金毛，非常喜欢和人互动。',
    shelterName: '爱心宠物之家',
    shelterDistance: '1.2公里',
    shelterLogo: 'https://cdn-icons-png.flaticon.com/512/3047/3047928.png',
    tags: ['已打疫苗'],
    category: 'dogs'
  },
  {
    id: 'nuomi',
    name: '糯米',
    breed: '暹罗猫',
    age: '1',
    ageUnit: '岁',
    gender: 'Female',
    distance: '3.8公里',
    image: 'https://images.unsplash.com/photo-1513245543132-31f507417b26?q=80&w=600&auto=format&fit=crop',
    price: '$80',
    location: '北京市朝阳区',
    weight: '4公斤',
    description: '糯米性格温顺，喜欢晒太阳。',
    shelterName: '喵喵救助站',
    shelterDistance: '3.8公里',
    shelterLogo: 'https://cdn-icons-png.flaticon.com/512/3047/3047928.png',
    tags: ['已绝育'],
    category: 'cats'
  },
   {
    id: 'luna',
    name: '露娜',
    breed: '虎斑猫',
    age: '1',
    ageUnit: '岁',
    gender: 'Female',
    distance: '3.8公里',
    image: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?q=80&w=600&auto=format&fit=crop',
    price: '$60',
    location: '北京市朝阳区',
    weight: '3.5公斤',
    description: '露娜很安静，适合喜欢安静环境的家庭。',
    shelterName: '流浪猫狗救助',
    shelterDistance: '3.8公里',
    shelterLogo: 'https://cdn-icons-png.flaticon.com/512/3047/3047928.png',
    tags: ['亲人'],
    category: 'cats'
  },
  {
    id: 'cooper',
    name: '库珀',
    breed: '比格犬',
    age: '3',
    ageUnit: '岁',
    gender: 'Male',
    distance: '2.5公里',
    image: 'https://images.unsplash.com/photo-1537151608828-ea2b11777ee8?q=80&w=600&auto=format&fit=crop',
    price: '$100',
    location: '广州市天河区',
    weight: '10公斤',
    description: '库珀精力充沛，需要大量的运动。',
    shelterName: '快乐汪汪',
    shelterDistance: '2.5公里',
    shelterLogo: 'https://cdn-icons-png.flaticon.com/512/3047/3047928.png',
    tags: ['活泼'],
    category: 'dogs'
  }
];